import { useEffect, useState } from 'react';
import {
  VStack,
  Field,
  Input,
  Button,
  DialogRoot,
  DialogContent,
  DialogHeader,
  DialogBody,
  DialogFooter,
  DialogBackdrop,
  DialogTitle,
  DialogCloseTrigger,
  createToaster,
} from '@chakra-ui/react';
import { SelectField, TextField } from '../../components';
import { pelangganAPI } from '../../services';
import type { Pelanggan as PelangganType } from '../../services';

const toaster = createToaster({ placement: 'top-end', pauseOnPageIdle: true });

interface Props {
  isOpen: boolean;
  onClose: () => void;
  pelanggan?: PelangganType | null;
  onSaved?: () => void;
}

export default function PelangganForm({ isOpen, onClose, pelanggan, onSaved }: Props) {
  const [formData, setFormData] = useState<{
    id_pelanggan?: string;
    nama: string;
    domisili: string;
    jenis_kelamin: 'PRIA' | 'WANITA' | '';
  }>({ nama: '', domisili: '', jenis_kelamin: '' });

  useEffect(() => {
    if (pelanggan) {
      setFormData({
        id_pelanggan: pelanggan.id_pelanggan,
        nama: pelanggan.nama,
        domisili: pelanggan.domisili,
        jenis_kelamin: pelanggan.jenis_kelamin ?? '',
      });
    } else {
      setFormData({ nama: '', domisili: '', jenis_kelamin: '' });
    }
  }, [pelanggan]);



  const handleSubmit = async () => {
    try {
      // id_pelanggan is generated by backend on create, so only require nama and jenis_kelamin
      if (!formData.nama || !formData.jenis_kelamin) {
        toaster.error({ title: 'Validasi Error', description: 'Field harus diisi' });
        return;
      }

      if (pelanggan) {
        await pelangganAPI.update(pelanggan.id_pelanggan, {
          nama: formData.nama,
          domisili: formData.domisili || undefined,
          jenis_kelamin: formData.jenis_kelamin as 'PRIA' | 'WANITA',
        });
        toaster.success({ title: 'Sukses', description: 'Pelanggan berhasil diupdate' });
      } else {
        // do not send id_pelanggan on create; backend will generate it
        await pelangganAPI.create({
          nama: formData.nama,
          domisili: formData.domisili || undefined,
          jenis_kelamin: formData.jenis_kelamin as 'PRIA' | 'WANITA',
        });
        toaster.success({ title: 'Sukses', description: 'Pelanggan berhasil ditambahkan' });
      }

      onSaved?.();
      onClose();
    } catch (error: unknown) {
      const err = error as { response?: { data?: { message?: string } } };
      toaster.error({ title: 'Error', description: err.response?.data?.message || 'Gagal menyimpan' });
    }
  };

  return (
    <DialogRoot open={isOpen} onOpenChange={(e) => { if (!e.open) onClose(); }}>
      <DialogBackdrop />
      <DialogContent position="fixed" top={{ base: '10vh', md: '12vh' }} left="50%" transform="translateX(-50%)" zIndex="overlay" maxW={{ base: '95vw', md: '600px' }}>
        <DialogHeader>
          <DialogTitle color="gray.900">{pelanggan ? 'Edit' : 'Tambah'} Pelanggan</DialogTitle>
          <DialogCloseTrigger />
        </DialogHeader>
        <DialogBody>
          <VStack gap={4}>
            {pelanggan && (
              <Field.Root>
                <Field.Label color="gray.900">ID Pelanggan</Field.Label>
                <Input value={pelanggan.id_pelanggan} disabled color="gray.900" />
              </Field.Root>
            )}

            <TextField label="Nama" placeholder="Nama pelanggan" value={formData.nama} onChange={(v) => setFormData({ ...formData, nama: v })} required />
            {/* Jenis Kelamin */}
            <SelectField
              label="Jenis Kelamin"
              items={[{ label: 'Pria', value: 'PRIA' }, { label: 'Wanita', value: 'WANITA' }]}
              value={formData.jenis_kelamin}
              onChange={(v) => setFormData({ ...formData, jenis_kelamin: v as 'PRIA' | 'WANITA' })}
              placeholder="Pilih jenis kelamin"
              required
            />
            <TextField label="Domisili" placeholder="Alamat" value={formData.domisili} onChange={(v) => setFormData({ ...formData, domisili: v })} />
          </VStack>
        </DialogBody>
        <DialogFooter>
          <Button variant="ghost" onClick={onClose}>Batal</Button>
          <Button colorScheme="blue" onClick={handleSubmit}>{pelanggan ? 'Update' : 'Tambah'}</Button>
        </DialogFooter>
      </DialogContent>
    </DialogRoot>
  );
}
